apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: cloudchamp
spec:
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongo"
